/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.LoginDAO;
import dao.UsuarioDAO;
import entidade.Login;
import entidade.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Augusto Fritz; Lucas Assis;
 */
public class IfrUsuario extends javax.swing.JInternalFrame {

    Usuario usuario;
    boolean edicao = false;
    Usuario usuarioEdicao = null;
    Login loginEdicao = null;

    /**
     * Creates new form IfrPessoa
     */
    public IfrUsuario(Usuario f) {
        initComponents();
        this.setTitle("Cadastro de Pessoas");
        this.usuario = f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCCargo = new javax.swing.JComboBox<String>();
        jTLogin = new javax.swing.JTextField();
        jPSenha = new javax.swing.JPasswordField();
        jBSalvar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();
        jLCriterio = new javax.swing.JLabel();
        jTCriterio = new javax.swing.JTextField();
        jBPesquisa = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneMouseClicked(evt);
            }
        });
        jTabbedPane.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabbedPaneKeyPressed(evt);
            }
        });

        jLabel2.setText("Cargo:*");

        jLabel1.setText("Nome:*");

        jLabel3.setText("Login:*");

        jLabel4.setText("Senha:*");

        jCCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));

        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNome)
                    .addComponent(jTLogin)
                    .addComponent(jPSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                .addContainerGap(270, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBSalvar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jBSalvar)
                .addContainerGap())
        );

        jTabbedPane.addTab("Cadastro", jPanel1);

        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableUsuario);

        jLCriterio.setText("Critério:");

        jBPesquisa.setText("Pesquisar");
        jBPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisaActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBEditar.setText("Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLCriterio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTCriterio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPesquisa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBExcluir)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCriterio)
                    .addComponent(jTCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBExcluir)
                    .addComponent(jBEditar))
                .addContainerGap())
        );

        jTabbedPane.addTab("Consulta", jPanel2);

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        // TODO add your handling code here:
        if (edicao) {
            Login l = new Login();
            l.setNome(jTLogin.getText());
            l.setSenha(jPSenha.getText());
            l.setId(loginEdicao.getId());

            LoginDAO ld = new LoginDAO();
            ld.update(l);

            Usuario u = new Usuario();
            u.setNome(jTNome.getText());
            String cargo = jCCargo.getItemAt(jCCargo.getSelectedIndex());
            u.setCargo(cargo.charAt(0));
            u.setId(usuarioEdicao.getId());

            UsuarioDAO ud = new UsuarioDAO();
            ud.update(u);

            jTLogin.setText("");
            jTNome.setText("");
            jPSenha.setText("");
            
            jTabbedPane.setEnabledAt(1, true);
            jTabbedPane.setSelectedIndex(1);
            edicao = false;
            

        } else {
            if (validaCampos()) {
                Login l = new Login();
                l.setNome(jTLogin.getText());
                l.setSenha(jPSenha.getText());

                LoginDAO ld = new LoginDAO();
                int idLogin = ld.salva(l);

                Usuario u = new Usuario();
                u.setNome(jTNome.getText());
                u.setLoginId(idLogin);
                String cargo = jCCargo.getItemAt(jCCargo.getSelectedIndex());
                u.setCargo(cargo.charAt(0));

                UsuarioDAO ud = new UsuarioDAO();
                ud.salva(u);

                jTLogin.setText("");
                jTNome.setText("");
                jPSenha.setText("");
            }
        }

    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        edicao = true;
        String id = jTableUsuario.getValueAt(jTableUsuario.getSelectedRow(), 0).toString();
        usuarioEdicao = new UsuarioDAO().consultarPorId(id);
        loginEdicao = new LoginDAO().consultarPorId(usuarioEdicao.getLoginId());
        jTabbedPane.setSelectedIndex(0);
        jTNome.setText(usuarioEdicao.getNome());
        jTLogin.setText(loginEdicao.getNome());
        jPSenha.setText(loginEdicao.getSenha());
        jBSalvar.setEnabled(true);
        if (usuarioEdicao.getCargo() == 'A') {
            jCCargo.setSelectedIndex(0);
        }
        if (usuarioEdicao.getCargo() == 'B') {
            jCCargo.setSelectedIndex(1);
        }
        if (usuarioEdicao.getCargo() == 'C') {
            jCCargo.setSelectedIndex(2);
        }
        if (usuarioEdicao.getCargo() == 'D') {
            jCCargo.setSelectedIndex(3);
        }
        jTabbedPane.setEnabledAt(1, false);
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jTabbedPaneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabbedPaneKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPaneKeyPressed

    private void jTabbedPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneMouseClicked
        switch (jTabbedPane.getSelectedIndex()) {
            case 0:
                jBEditar.setEnabled(false);
                jBSalvar.setEnabled(true);
                break;
            case 1:
                jBEditar.setEnabled(true);
                jBSalvar.setEnabled(false);
                break;
        }
    }//GEN-LAST:event_jTabbedPaneMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisaActionPerformed
        // TODO add your handling code here:
        String criterio = jTCriterio.getText();
        new UsuarioDAO().popularTabela(jTableUsuario, criterio);
    }//GEN-LAST:event_jBPesquisaActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        // TODO add your handling code here:
        System.out.println(jTableUsuario.getValueAt(jTableUsuario.getSelectedRow(), 0));
        String id = jTableUsuario.getValueAt(jTableUsuario.getSelectedRow(), 0).toString();
        String idLogin = jTableUsuario.getValueAt(jTableUsuario.getSelectedRow(), 3).toString();
        System.out.println(id);
        System.out.println(idLogin);
        Usuario u = new Usuario();
        u.setId(Integer.parseInt(id));
        u.setLoginId(Integer.parseInt(idLogin));
        new UsuarioDAO().exclui(u);
        jBPesquisaActionPerformed(null);


    }//GEN-LAST:event_jBExcluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBPesquisa;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCCargo;
    private javax.swing.JLabel jLCriterio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCriterio;
    private javax.swing.JTextField jTLogin;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTableUsuario;
    // End of variables declaration//GEN-END:variables

    public boolean validaCampos() {
        String mensagem = "Confira esses campos:\n";
        if (jTNome.getText().length() < 2) {
            mensagem += "- Nome\n";
        }
        if (jTLogin.getText().length() < 2) {
            mensagem += "- Login\n";
        }
        if (jPSenha.getText().length() < 2) {
            mensagem += "- Senha\n";
        }
        if (mensagem.equals("Confira esses campos:\n")) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, mensagem);
            return false;
        }
    }
}
